# NNI experiment configuration for YOLOv8 Neural Architecture Search and Hyperparameter Tuning
experimentName: YOLOv8_NAS_Tuning
searchSpaceFile: search_space.json

# Command to run for each trial
trialCommand: python train_yolo.py --data_yaml data/dataset.yaml

# Number of concurrent trials to run
trialConcurrency: 1

# Maximum number of trials to run
maxTrialNumber: 20

# Maximum duration of the experiment (5 hours)
maxExperimentDuration: 15h

# Tuning algorithm configuration
tuner:
  name: TPE  # Tree-structured Parzen Estimator algorithm
  classArgs:
    optimize_mode: maximize  # Maximize the metric (mAP)
    seed: 42

# Training service configuration for local execution
trainingService:
  platform: local
  useActiveGpu: true  # Use GPUs that are already active
  maxTrialNumberPerGpu: 1  # Run one trial per GPU
  gpuIndices: 0  # Use GPU 0 (add more indices separated by comma for multi-GPU)

# Early stopping configuration (stop trials that are unlikely to be the best)
assessor:
  name: Medianstop
  classArgs:
    optimize_mode: maximize
    start_step: 5
    
# Log configuration
logDir: logs
logLevel: info